CREATE INDEX "admin_audit_log_admin_idx" ON "admin_audit_log" USING btree ("admin_id");--> statement-breakpoint
CREATE INDEX "admin_audit_log_action_idx" ON "admin_audit_log" USING btree ("action");--> statement-breakpoint
CREATE INDEX "admin_audit_log_target_type_idx" ON "admin_audit_log" USING btree ("target_type");--> statement-breakpoint
CREATE INDEX "admin_audit_log_created_idx" ON "admin_audit_log" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "badges_type_idx" ON "badges" USING btree ("type");--> statement-breakpoint
CREATE INDEX "blood_donations_donor_idx" ON "blood_donations" USING btree ("donor_id");--> statement-breakpoint
CREATE INDEX "blood_donations_date_idx" ON "blood_donations" USING btree ("donation_date");--> statement-breakpoint
CREATE INDEX "blood_donations_type_idx" ON "blood_donations" USING btree ("donation_type");--> statement-breakpoint
CREATE INDEX "blood_donations_processed_idx" ON "blood_donations" USING btree ("processed");--> statement-breakpoint
CREATE INDEX "inventory_blood_group_idx" ON "blood_inventory" USING btree ("blood_group");--> statement-breakpoint
CREATE INDEX "blood_issuance_blood_group_idx" ON "blood_issuance" USING btree ("blood_group");--> statement-breakpoint
CREATE INDEX "blood_issuance_date_idx" ON "blood_issuance" USING btree ("issuance_date");--> statement-breakpoint
CREATE INDEX "blood_issuance_admin_idx" ON "blood_issuance" USING btree ("admin_id");--> statement-breakpoint
CREATE INDEX "bulk_operations_log_admin_idx" ON "bulk_operations_log" USING btree ("admin_id");--> statement-breakpoint
CREATE INDEX "bulk_operations_log_operation_idx" ON "bulk_operations_log" USING btree ("operation");--> statement-breakpoint
CREATE INDEX "bulk_operations_log_target_type_idx" ON "bulk_operations_log" USING btree ("target_type");--> statement-breakpoint
CREATE INDEX "bulk_operations_log_created_idx" ON "bulk_operations_log" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "comm_logs_from_user_idx" ON "communication_logs" USING btree ("from_user_id");--> statement-breakpoint
CREATE INDEX "comm_logs_to_user_idx" ON "communication_logs" USING btree ("to_user_id");--> statement-breakpoint
CREATE INDEX "comm_logs_type_idx" ON "communication_logs" USING btree ("communication_type");--> statement-breakpoint
CREATE INDEX "comm_logs_status_idx" ON "communication_logs" USING btree ("status");--> statement-breakpoint
CREATE INDEX "appointments_donor_idx" ON "donation_appointments" USING btree ("donor_id");--> statement-breakpoint
CREATE INDEX "appointments_seeker_idx" ON "donation_appointments" USING btree ("seeker_id");--> statement-breakpoint
CREATE INDEX "appointments_status_idx" ON "donation_appointments" USING btree ("status");--> statement-breakpoint
CREATE INDEX "appointments_date_idx" ON "donation_appointments" USING btree ("appointment_date");--> statement-breakpoint
CREATE INDEX "appointments_status_date_idx" ON "donation_appointments" USING btree ("status","appointment_date");--> statement-breakpoint
CREATE INDEX "donation_history_user_idx" ON "donation_history" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "donation_history_date_idx" ON "donation_history" USING btree ("donation_date");--> statement-breakpoint
CREATE INDEX "donation_history_type_idx" ON "donation_history" USING btree ("donation_type");--> statement-breakpoint
CREATE INDEX "donations_donor_id_idx" ON "donations" USING btree ("donor_id");--> statement-breakpoint
CREATE INDEX "donations_blood_group_idx" ON "donations" USING btree ("blood_group");--> statement-breakpoint
CREATE INDEX "donations_date_idx" ON "donations" USING btree ("donation_date");--> statement-breakpoint
CREATE INDEX "donations_stats_idx" ON "donations" USING btree ("blood_group","donation_date");--> statement-breakpoint
CREATE INDEX "education_history_user_idx" ON "education_history" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "education_history_type_idx" ON "education_history" USING btree ("institution_type");--> statement-breakpoint
CREATE INDEX "emergency_blood_req_blood_group_idx" ON "emergency_blood_requests" USING btree ("blood_group");--> statement-breakpoint
CREATE INDEX "emergency_blood_req_status_idx" ON "emergency_blood_requests" USING btree ("status");--> statement-breakpoint
CREATE INDEX "emergency_blood_req_urgency_idx" ON "emergency_blood_requests" USING btree ("urgency_level");--> statement-breakpoint
CREATE INDEX "emergency_management_idx" ON "emergency_blood_requests" USING btree ("blood_group","status","urgency_level");--> statement-breakpoint
CREATE INDEX "emergency_blood_req_user_idx" ON "emergency_blood_requests" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "emergency_blood_req_created_idx" ON "emergency_blood_requests" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "emergency_blood_group_idx" ON "emergency_requests" USING btree ("blood_group");--> statement-breakpoint
CREATE INDEX "emergency_status_idx" ON "emergency_requests" USING btree ("status");--> statement-breakpoint
CREATE INDEX "emergency_requester_idx" ON "emergency_requests" USING btree ("requester_id");--> statement-breakpoint
CREATE INDEX "emergency_dashboard_idx" ON "emergency_requests" USING btree ("blood_group","status");--> statement-breakpoint
CREATE INDEX "messages_sender_idx" ON "messages" USING btree ("sender_id");--> statement-breakpoint
CREATE INDEX "messages_recipient_idx" ON "messages" USING btree ("recipient_id");--> statement-breakpoint
CREATE INDEX "messages_is_read_idx" ON "messages" USING btree ("is_read");--> statement-breakpoint
CREATE INDEX "messages_conversation_idx" ON "messages" USING btree ("sender_id","recipient_id");--> statement-breakpoint
CREATE INDEX "notification_templates_type_idx" ON "notification_templates" USING btree ("type");--> statement-breakpoint
CREATE INDEX "notification_templates_is_active_idx" ON "notification_templates" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "notifications_user_id_idx" ON "notifications" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "notifications_is_read_idx" ON "notifications" USING btree ("is_read");--> statement-breakpoint
CREATE INDEX "notification_center_idx" ON "notifications" USING btree ("user_id","is_read");--> statement-breakpoint
CREATE INDEX "notifications_type_idx" ON "notifications" USING btree ("type");--> statement-breakpoint
CREATE INDEX "otp_codes_user_idx" ON "otp_codes" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "otp_codes_identifier_idx" ON "otp_codes" USING btree ("identifier");--> statement-breakpoint
CREATE INDEX "otp_codes_purpose_idx" ON "otp_codes" USING btree ("purpose");--> statement-breakpoint
CREATE INDEX "otp_codes_is_used_idx" ON "otp_codes" USING btree ("is_used");--> statement-breakpoint
CREATE INDEX "otp_codes_expires_idx" ON "otp_codes" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "privacy_settings_user_idx" ON "privacy_settings" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "reactivation_requests_user_idx" ON "reactivation_requests" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "reactivation_requests_status_idx" ON "reactivation_requests" USING btree ("status");--> statement-breakpoint
CREATE INDEX "reactivation_requests_created_idx" ON "reactivation_requests" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "search_activity_user_idx" ON "search_activity" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "search_activity_session_idx" ON "search_activity" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "search_activity_created_idx" ON "search_activity" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "analytics_metric_type_idx" ON "system_analytics" USING btree ("metric_type");--> statement-breakpoint
CREATE INDEX "analytics_created_date_idx" ON "system_analytics" USING btree ("created_date");--> statement-breakpoint
CREATE INDEX "analytics_dashboard_idx" ON "system_analytics" USING btree ("metric_type","created_date");--> statement-breakpoint
CREATE INDEX "system_settings_category_idx" ON "system_settings" USING btree ("category");--> statement-breakpoint
CREATE INDEX "system_settings_key_idx" ON "system_settings" USING btree ("key");--> statement-breakpoint
CREATE INDEX "testimonials_reviewer_idx" ON "testimonials" USING btree ("reviewer_id");--> statement-breakpoint
CREATE INDEX "testimonials_reviewee_idx" ON "testimonials" USING btree ("reviewee_id");--> statement-breakpoint
CREATE INDEX "testimonials_rating_idx" ON "testimonials" USING btree ("rating");--> statement-breakpoint
CREATE INDEX "two_factor_auth_user_idx" ON "two_factor_auth" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "two_factor_auth_enabled_idx" ON "two_factor_auth" USING btree ("is_enabled");--> statement-breakpoint
CREATE INDEX "user_badges_user_idx" ON "user_badges" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_badges_badge_idx" ON "user_badges" USING btree ("badge_id");--> statement-breakpoint
CREATE INDEX "user_badges_earned_at_idx" ON "user_badges" USING btree ("earned_at");--> statement-breakpoint
CREATE INDEX "user_verifications_user_idx" ON "user_verifications" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_verifications_status_idx" ON "user_verifications" USING btree ("status");--> statement-breakpoint
CREATE INDEX "user_verifications_type_idx" ON "user_verifications" USING btree ("verification_type");--> statement-breakpoint
CREATE INDEX "users_blood_group_idx" ON "users" USING btree ("blood_group");--> statement-breakpoint
CREATE INDEX "users_district_idx" ON "users" USING btree ("district");--> statement-breakpoint
CREATE INDEX "users_division_idx" ON "users" USING btree ("division");--> statement-breakpoint
CREATE INDEX "users_is_available_idx" ON "users" USING btree ("is_available");--> statement-breakpoint
CREATE INDEX "users_donor_search_idx" ON "users" USING btree ("blood_group","district","is_available");--> statement-breakpoint
CREATE INDEX "users_last_donation_date_idx" ON "users" USING btree ("last_donation_date");--> statement-breakpoint
CREATE INDEX "verification_requests_user_idx" ON "verification_requests" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "verification_requests_status_idx" ON "verification_requests" USING btree ("status");--> statement-breakpoint
CREATE INDEX "verification_requests_type_idx" ON "verification_requests" USING btree ("verification_type");--> statement-breakpoint
CREATE INDEX "verification_requests_created_idx" ON "verification_requests" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "work_history_user_idx" ON "work_history" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "work_history_start_date_idx" ON "work_history" USING btree ("start_date");